FROM ubuntu
RUN apt-get update 
RUN apt-get install -y python3 
RUN apt-get clean
RUN apt-get install -y python3-matplotlib
RUN apt-get install -y python3-numpy
COPY app.py /opt/app.py
CMD python3 /opt/app.py
